[package]
name = "leet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
test-case = "3.3.1"

[[bench]]
name = "trapping_rain_water"
harness = false

[[bench]]
name = "trapping_rain_water_v2"
harness = false

[[bench]]
name = "trapping_rain_water_v3"
harness = false

[[bench]]
name = "merge_sorted"
harness = false

[profile.release]
debug = true
